### ISSUE TITLE
Inkscape issues

### ISSUE THREAD

**Issue by ge0rgecz** [lassekongo83/plano-theme#10]
multiple design issues in Inkscape (GNOME Shell 3.24.0)

screenshot:
![inkscape bugs - adwaita vs plano](https://cloud.githubusercontent.com/assets/8430061/25374444/bb84e61a-299d-11e7-9ccf-65c95dc4b0f6.png)

**Comment by lassekongo83** [comment]
Install `gtk2-engines-murrine` and/or `gtk2-engines-pixbuf` if you're on Debian/Ubuntu/Mint. 

For other distros install the `gtk-engines` or `gtk2-engines` packages and the murrine gtk2 engines.
