### ISSUE TITLE
Ugly LightDM Panel

### ISSUE THREAD

**Issue by chuutatsu** [lassekongo83/plano-theme#12]
Plano had been my favorite flat theme. However, there was one small issue that bothered me.

When using Plano as the lightdm theme... the lightdm panel is too bright and its fonts are white too, making it very difficult to see. But the login window is okay.

![img_20170605_111237](https://cloud.githubusercontent.com/assets/24815847/26770372/816f3aa8-49e0-11e7-8cf1-2edd21808e6a.jpg)

Sorry for bad phone camera, I can't take screenshot of lightdm.

I am using GTK 3.22 in Manjaro.

**Comment by lassekongo83** [comment]
I removed the lightdm theme because of limited testing options. I don't even have it installed. The default lightdm theme should be good enough.
