### ISSUE TITLE
gtk2 theme does not work

### ISSUE THREAD

**Issue by kazysmaster** [lassekongo83/plano-theme#13]
I installed latest theme version from github as of today.
![image](https://user-images.githubusercontent.com/1195029/27707229-3d1b1912-5d1d-11e7-9f74-510cf082d81c.png)
I'm using fedora 26
gtk3-3.22.16-1.fc26.x86_64
gtk2-2.24.31-4.fc26.x86_64
gtk2-engines-2.20.2-12.fc26.x86_64
gtk-murrine-engine-0.98.2-11.fc26.x86_64

**Comment by lassekongo83** [comment]
Can't reproduce. Do you have the same problem with themes like [Arc](https://github.com/horst3180/arc-theme) or [Greybird](https://github.com/shimmerproject/Greybird)?

**Comment by kazysmaster** [comment]
Yes greybird and Arc seem to work fine. I do not get any warnings when gtk2 application is started. Is there any env. variable that may help me to debug the problem?

**Comment by kazysmaster** [comment]
I found the cause. I installed the theme into .local/share/themes. Moving the theme to .themes folder fixes the problem.  I would be nice if the theme supported both locations, but that is probably another matter.
