### ISSUE TITLE
The menu underline is not visible in VLC (2.2.6)

### ISSUE THREAD

**Issue by kepler2** [lassekongo83/plano-theme#19]
Hello!

Thanks for you work.

I have found something. In VLC, the menu underline is not visible. (note that in Thunar, for example, is visible)

Underline:
![underline](https://user-images.githubusercontent.com/18610924/29309084-eda0e9b2-81b0-11e7-935d-c02a90b66ff0.png)

No underline:
![no_underline](https://user-images.githubusercontent.com/18610924/29309099-f574661e-81b0-11e7-90c0-ee7271942c74.png)

Thanks!

**Comment by lassekongo83** [comment]
VLC is a not a GTK application, it's QT. That can cause the consistency to be a bit off on some parts of the theme as a side effect. In this case I believe the menubar in QT applications use a larger padding and can't read the one specified in the GTK theme.

**Comment by kepler2** [comment]
Sorry I have an eye for consistency :), it would be nice to have consistent look between gtk / qt apps, but i guess it's up to you. (to be honest, the most consistent theme - not really the best looking and not really my favourite - is Arc theme. In this particular case, Arc theme has different selection highlight than Plano that it applies to both cases)

**Comment by kepler2** [comment]
Hey :). So... there is no way to fix this? It doesn't happen for Greybird, Numix etc.

**Comment by lassekongo83** [comment]
The selection indicator is an image which can't be used in the QT-GTK style. I swapped the underline to a single color instead.

**Comment by kepler2** [comment]
Thanks! Nice fix, now there is consistency between applications. (I tried in Thunar and VLC). Maybe some people will be upset because there is no underline anymore? :)
