### ISSUE TITLE
Consistency with LibreOffice's toolbars

### ISSUE THREAD

**Issue by Art-2** [lassekongo83/plano-theme#20]
There are 2 visible lines over the toolbars in LibreOffice, (it even give a 3D effect to the toolbar).

Could this look like others GTK apps? (Thunar and Lutris for reference)
![captura de pantalla_2017-08-16_20-54-04](https://user-images.githubusercontent.com/12375357/29395089-b574e55e-82cb-11e7-9897-a653be425cd6.png)

**Comment by lassekongo83** [comment]
The borders should go away if you install `libreoffice-gtk3`.
