### ISSUE TITLE
Dark titlebar variant

### ISSUE THREAD

**Issue by jderose9** [lassekongo83/plano-theme#22]
It would be great if a variant of the gtk theme was maintained that had dark window titebars.

**Comment by lassekongo83** [comment]
Might be a project once I'm done with https://github.com/lassekongo83/amber-theme
At least then I'll have some better scss to work with.

**Comment by philgood** [comment]
Any further updates on a dark titlebar variant?

**Comment by lassekongo83** [comment]
It's a slow process, so it will be done when it's done. Still not quite happy with what I have.

**Comment by philgood** [comment]
Thanks for the prompt update @lassekongo83

**Comment by fblais** [comment]
Would like to see a darker titlebar as well.  :)
Thanks in advance.

**Comment by lassekongo83** [comment]
To enable the dark titlebar, open: `gtk-3.0/gtk.scss` and change `$dark_header: 'false';` to `$dark_header: 'true';`

You'll need to have `sassc` installed. Then run: `sh parse-sass.sh` and reload the theme.

I'll probably work on the gtk-2.0 menubar, xfwm4 theme, and an installation script later.

**Comment by fblais** [comment]
Thanks!
