### ISSUE TITLE
[Non-Issue] What is the terminal colour scheme for your screenshot?

### ISSUE THREAD

**Issue by berkiyo** [lassekongo83/plano-theme#23]
Hi there,

I really love the theme you've create and it just works perfectly with the XFCE desktop environment! Keep up the amazing work!

There is one thing I would want to know and that is the terminal colour scheme you have on the project page, if possible, could you share it? It looks like solarized-dark but I could be wrong. 

Thanks!

**Comment by lassekongo83** [comment]
It's solarized-dark with slightly brighter text color.
