### ISSUE TITLE
right click on nautilus, firefox, etc hav no hover indicator

### ISSUE THREAD

**Issue by as3mbus** [lassekongo83/plano-theme#24]
just as the title says it just displays the menu. but it seems when i right click on panel works fine

**Comment by lassekongo83** [comment]
Need more info. Which desktop environment, distribution, version of software?

**Comment by as3mbus** [comment]
on xubuntu 16.04 and also using the master branch for this theme

**Comment by lassekongo83** [comment]
There's no supported version for 16.04 which uses GTK 3.18. This theme only works in GTK 3.20+.
