### ISSUE TITLE
Buttons & tab color in RB

### ISSUE THREAD

**Issue by timur-davletshin** [lassekongo83/plano-theme#29]
1. Right side of buttons in RB is missing blue glow (Debian Stable, x64 bit).
2. Tabs background is white in RB and grey in Evolution. Grey is more consistent IMHO.

Thanks in advance!

![rb](https://user-images.githubusercontent.com/23050090/44479192-9015bd00-a648-11e8-9575-d5a639751144.png)

**Comment by lassekongo83** [comment]
1st one is a drawback of using a box-shadow on linked buttons, nothing can be done about it.
2nd one is intended. Those are listview headers and not tabs.
