### ISSUE TITLE
TODO: Create better looking switches and checkboxes

### ISSUE THREAD

**Issue by lassekongo83** [lassekongo83/plano-theme#3]

**Comment by imranmunshi** [comment]
Same here
![screenshot_2017-04-17-15 33 13](https://cloud.githubusercontent.com/assets/5736192/25086086/3669c010-2383-11e7-8e6a-b40dc158b1d8.png)
I expected something similar to Zukitre, but there are no borders or indicators to show if there exists a checkbox or radio button

**Comment by imranmunshi** [comment]
For reference, here is zukitre
![screenshot_2017-04-17-15 35 01](https://cloud.githubusercontent.com/assets/5736192/25086132/7b33198a-2383-11e7-8396-28d8778f9482.png)

**Comment by lassekongo83** [comment]
That's the original intended behavior in menus. The same as Adwaita.

**Comment by imranmunshi** [comment]
Any update regarding this? I want to use this theme as my main theme

**Comment by lassekongo83** [comment]
I think you misunderstood the original intended behavior. There's nothing to do except polishing the existing ones with better CSS. (Just need to figure out something that looks good.) A checkbox is not supposed to be shown for each menu item, just like the way Adwaita works. Zukitre uses a lot of png assets. Plano just use 2 simple glyphs that works for both the dark and light theme making it a lot easier to maintain. There is no need to show a graphic for all of them as the default selection will always be shown as selected anyways.

**Comment by imranmunshi** [comment]
There should at least be an indication of existence of something that can be checked. If this is the intended behaviour then checkboxes and radios would be indistuingishable since they are invisible when unchecked.
They should have some indication of their distinc existence.

Besides that, the theme looks gorgeous

**Comment by lassekongo83** [comment]
> There should at least be an indication of existence of something that can be checked.
Yeah, the default selected item is.

**Comment by imranmunshi** [comment]
How will someone differentiate between unselected checkboxes and unselected radio buttons? Both of them look same

**Comment by imranmunshi** [comment]
This theme is not usable unless there are distinctively visible checkboxes and radio buttons. Will they be added some time soon?

**Comment by lassekongo83** [comment]
If there's no dot, it's not active, if there is one it is. Same as the default Gnome theme. Not visible enough?

**Comment by imranmunshi** [comment]
In default GNOME theme even the unselected radio buttons and checkboxes are distinctively visible but not in this theme.

Zukitre vs Plano, look at the difference. No one can tell whether a "selectable" check box or radio button is present

**Comment by lassekongo83** [comment]
Ok, I see what you mean now. Will have a fix ready soon enough.
