### ISSUE TITLE
LO → Some issues

### ISSUE THREAD

**Issue by timur-davletshin** [lassekongo83/plano-theme#30]
Not sure if this can be fixed (LO + GTK2 engine)

1. Dropdown menu button is bigger than menu itself.
2. LO start screen background is a bit darker than typical background.

Thanks for your themes, I use them for several years!

![lo](https://user-images.githubusercontent.com/23050090/44480113-1c28e400-a64b-11e8-9dea-5b9198d9eab4.png)
![lo2](https://user-images.githubusercontent.com/23050090/44480116-1df2a780-a64b-11e8-8643-4b69e743afec.png)

**Comment by lassekongo83** [comment]
1st one could be fixed by simply removing the pixmap buttons, but then the buttons wouldn't look the same as the GTK3 ones. I would just advise people to install libreoffice-gtk3 instead.

2nd one is intended. Sidebars use a slightly darker color than the rest.

**Comment by Art-2** [comment]
1. Qt5 based programs has this problem too and even if it does not look same as the GTK3 ones, I think it would be better.

for example: qpdfview
![plano](https://user-images.githubusercontent.com/12375357/49768266-62a95980-fca1-11e8-959a-de3106dc241b.jpeg)
From top to bottom: Fusion, Zukrite and Plano themes.
