### ISSUE TITLE
Windows have no borders

### ISSUE THREAD

**Issue by kepler2** [lassekongo83/plano-theme#35]
Hey again.

While using this nice theme, I noticed that windows have no borders. 

Can you take a look below?
It looks a little strange when there is gray on gray, something like that.

![border](https://user-images.githubusercontent.com/18610924/50889760-70b5db80-1401-11e9-8228-3fea2971f44d.png)

Thanks!

**DE**: XFCE 4.12.

**Comment by lassekongo83** [comment]
I designed the xfwm4 theme with a compositor. Xfwm4 have its own, but there's also compton. So I've always had a shadow behind the wm. Not really sure if I want to add a dark border on the xfwm4 theme.

**Comment by kepler2** [comment]
Thanks for the response.

So the "workaround" is to use compton with shadows or the XFCE compositor with shadows.
