### ISSUE TITLE
Window control buttons on Firefox

### ISSUE THREAD

**Issue by Art-2** [lassekongo83/plano-theme#36]
The control buttons on Firefox are wider than the normal, this was not present before the lastest release.
![captura de pantalla_2019-01-09_15-00-07](https://user-images.githubusercontent.com/12375357/50928669-e54c4280-1420-11e9-89be-d9f0fa533ceb.png)

I am using Firefox with the title bar hided:
_Menu > Customize > [ ] Title Bar_
 
DE: Xfce 4.13

Sorry if this is intented and happy new year.

**Comment by lassekongo83** [comment]
Can't really figure out how to style Firefox CSD. My guess would be that this should have fixed it:

```sass
#MozillaGtkWidget.background  {
  &.default-decoration,
  headerbar.titlebar {
    button.titlebutton { @extend %titlebutton; }
  }
}
```

But nothing happens whatever I try.
