### ISSUE TITLE
Is there a way to know the version of Plano theme i have installed is up to date (updated) or not?

### ISSUE THREAD

**Issue by PranavBhattrai** [lassekongo83/plano-theme#40]
Is this theme is available in any Snap, Flatpack or Aptitude repository? 

It would be easier if this theme is officially supported in other repositories rather than just be limited in this GitHub platform. Because we can't run update command from Github, is there?

**Comment by lassekongo83** [comment]
Not yet. I've not read the documentation on how to maintain snap/flatpak/ppa packages.

> Because we can't run update command from Github, is there?

It's possible, but you would have to write a script that pulls the updates at a regular interval using `cron`. I've not looked into that either.
