### ISSUE TITLE
When i tried updating plano theme, this is what happened:

### ISSUE THREAD

**Issue by PranavBhattari** [lassekongo83/plano-theme#42]
> <pre><font color="#00AA00"><b>pranav@inspiron-5548</b></font>:<font color="#0000AA"><b>~</b></font>$ cd ~/.themes/
> <font color="#00AA00"><b>pranav@inspiron-5548</b></font>:<font color="#0000AA"><b>~/.themes</b></font>$ ls
> <font color="#0000AA"><b>delorean-dark-theme-3.6-G</b></font>
> <font color="#AA0000"><b>delorean_dark_theme_3_6_g__vs_2_56_by_killhellokitty-d5nnoxt.zip</b></font>
> <font color="#0000AA"><b>plano-theme</b></font>
> <font color="#00AA00"><b>pranav@inspiron-5548</b></font>:<font color="#0000AA"><b>~/.themes</b></font>$ cd plano-theme
> <font color="#00AA00"><b>pranav@inspiron-5548</b></font>:<font color="#0000AA"><b>~/.themes/plano-theme</b></font>$ ls
> <font color="#0000AA"><b>gnome-shell</b></font>  index.theme  <font color="#AA00AA"><b>plano.png</b></font>
> <font color="#0000AA"><b>gtk-2.0</b></font>      LICENSE      README.md
> <font color="#0000AA"><b>gtk-3.0</b></font>      <font color="#0000AA"><b>openbox-3</b></font>    <font color="#0000AA"><b>xfwm4</b></font>
> <font color="#00AA00"><b>pranav@inspiron-5548</b></font>:<font color="#0000AA"><b>~/.themes/plano-theme</b></font>$ ```bash
> &gt; cd ~/.themes/plano-theme
> &gt; git pull
> &gt; ```
> <font color="#00AA00"><b>pranav@inspiron-5548</b></font>:<font color="#0000AA"><b>~/.themes/plano-theme</b></font>$ ls
> <font color="#00AA00"><b>pranav@inspiron-5548</b></font>:<font color="#0000AA"><b>~/.themes/plano-theme</b></font>$ cd ..
> <font color="#00AA00"><b>pranav@inspiron-5548</b></font>:<font color="#0000AA"><b>~/.themes</b></font>$ ls
> <font color="#00AA00"><b>pranav@inspiron-5548</b></font>:<font color="#0000AA"><b>~/.themes</b></font>$ cd ..
> <font color="#00AA00"><b>pranav@inspiron-5548</b></font>:<font color="#0000AA"><b>~</b></font>$ exit
> exit
> remote: Enumerating objects: 42, done.
> remote: Counting objects: 100% (42/42), done.
> remote: Compressing objects: 100% (8/8), done.
> remote: Total 52 (delta 36), reused 40 (delta 34), pack-reused 10
> Unpacking objects: 100% (52/52), done.
> From https://github.com/lassekongo83/plano-theme
>    5200616..e083c7e  master     -&gt; origin/master
> org.gnome.Shell already exists on bus and --replace not specified
> <font color="#00AA00"><b>pranav@inspiron-5548</b></font>:<font color="#0000AA"><b>~/.themes/plano-theme</b></font>$ 
> </pre>

**Did I work? I don't know. I don't think it worked.** 
"_org.gnome.Shell already exists on bus and --replace not specified_" dialogue probably mean something.

**Comment by lassekongo83** [comment]
You can't run markdown syntax in your shell. (Maybe you're viewing the README.md file as raw. Don't do that.). Just copy and paste this:

cd ~/.themes/plano-theme && git pull

**Comment by PranavBhattari** [comment]
@lassekongo83 
<pre><font color="#00AA00"><b>pranav@inspiron-5548</b></font>:<font color="#0000AA"><b>~/.themes/plano-theme</b></font>$ git pull
remote: Enumerating objects: 13, done.
remote: Counting objects: 100% (13/13), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 13 (delta 6), reused 13 (delta 6), pack-reused 0
Unpacking objects: 100% (13/13), done.
From https://github.com/lassekongo83/plano-theme
   e083c7e..f6d1eba  master     -&gt; origin/master
Updating e083c7e..f6d1eba
Fast-forward
 gtk-3.0/_apps.scss   | 2 <font color="#00AA00">+</font><font color="#AA0000">-</font>
 gtk-3.0/_common.scss | 2 <font color="#00AA00">++</font>
 gtk-3.0/gtk-dark.css | 2 <font color="#00AA00">++</font>
 gtk-3.0/gtk.css      | 2 <font color="#00AA00">++</font>
 4 files changed, 7 insertions(+), 1 deletion(-)
</pre>

Don't i have to clean or delete old files when there is new one available?

**Comment by lassekongo83** [comment]
When you use git there's no need to remove the old files.
