### ISSUE TITLE
Feature request: Decrease the size of notification panel if possible. Its too huge. And cover larger part of the screen.

### ISSUE THREAD

**Issue by PranavBhattarai** [lassekongo83/plano-theme#45]
As u can see here:
![Screenshot from 2019-11-17 09-09-10](https://user-images.githubusercontent.com/32763112/69002576-0a9bbe00-091a-11ea-9f36-7137ff011341.png)
This creates a complete distraction when u are multi-tasking, watching a movie, clearing wanted notification, etc.

If we can shrink this size, it would have been really great.
I like how the Top menu panel is shrinked. I wish the same thing for this ugly huge notification panel.

_Distro: Ubuntu 19.10
DE: GNOME 3.34.1_

**Comment by lassekongo83** [comment]
It's not possible to change the size of it from my understanding. Seems to be hard-coded.

**Comment by PranavBhattarai** [comment]
> It's not possible 

Oh, that's what I thought. That's why I used word "if possible" in the heading.

_I hope u are 100% sure about this. I am closing this desperate attempt. But I do want you to think about it & do some magic :-D._
