### ISSUE TITLE
I love this extension but ever since I have upgraded to Ubuntu 19.10, I have this probem.

### ISSUE THREAD

**Issue by PranavBhattarai** [lassekongo83/plano-theme#46]
I love the idea of transparent + in-transparent area in the taskbar but this concept has a terrible effect on notification area as u can below screenshot images:

Image under Plano theme
![Image under Plano theme. ](https://user-images.githubusercontent.com/32763112/69312136-3d192400-0c56-11ea-98df-c7cb33660bbb.png)

**VS**

Image under Yaru dark theme
![Image under Yaru dark theme](https://user-images.githubusercontent.com/32763112/69312202-61750080-0c56-11ea-8786-6833c7d660f3.png)

I wish the Plano theme has the same notification panel's color effect like in Yaru. _Yaru is an opensource product made my Ubuntu and is available in Github. Can't we steal some code from them that would make the notification panel look more beautiful, vibrant and most importantly visible words/sentences in Notification panel.?_

**Comment by lassekongo83** [comment]
Let me know if that fix changed anything.

**Comment by PranavBhattarai** [comment]
> Let me know if that fix changed anything.

I used git-pull to update Plano theme > Rebooted my Laptop to see any effect/changes > No Change = Same old look  

```
pranav@Exam:~/.themes/plano-theme$ git pull
remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 5 (delta 0), reused 1 (delta 0), pack-reused 0
Unpacking objects: 100% (5/5), done.
From https://github.com/lassekongo83/plano-theme
   bfbe7be..951fc7f  master     -> origin/master
Updating bfbe7be..951fc7f
Fast-forward
 gnome-shell/gnome-shell-sass/_common.scss | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)
```

**Comment by lassekongo83** [comment]
This is really strange. I can't see any bright background colors anywhere in the CSS. Is it a 3rd party extension you're using?

**Comment by PranavBhattarai** [comment]
@lassekongo83 These are the total extension I am using.
![Screenshot from 2019-11-22 10-53-39](https://user-images.githubusercontent.com/32763112/69399495-731ddd00-0d16-11ea-8ec3-c6a349770f26.png)

**Comment by PranavBhattarai** [comment]
Inside **Tweaks** > **Apperance**
![Screenshot from 2019-11-22 10-55-12](https://user-images.githubusercontent.com/32763112/69399536-9cd70400-0d16-11ea-99a3-64e84069e25a.png)

**Comment by lassekongo83** [comment]
Well, I guess it's time for a rewrite of the Plano shell theme at some point. Its code base is getting old.

**Comment by PranavBhattarai** [comment]
@lassekongo83 I will be waiting...

**Comment by PranavBhattarai** [comment]
I will be closing this bug report since it's based on a non-LTS distro which will no longer be tracking done by me. The distro verson will itself declared dead after a few months.

Now new bug reports are address with new Ubuntu 20.04 LTS release.
