### ISSUE TITLE
New Plano update = New problem in Ubuntu 19.10 where 3 icons are hidden from Top menu.

### ISSUE THREAD

**Issue by PranavBhattarai** [lassekongo83/plano-theme#49]
As u can see in this screenshot:
![Screenshot from 2020-01-11 13-14-01](https://user-images.githubusercontent.com/32763112/72200670-52e7e000-3474-11ea-910e-f46df186d862.png)

Those 3 icons (in sequence) went missing:
1. Settings
2. Lock
3. Power Off
_(Optional: 4. A small downward-facing arrow which I don't really much care but it would be nice to have it.)_

This happened after recent pull updates_(Except 4th optional I mentioned above)_.
How Plano theme should look:
![Screenshot from 2020-01-11 13-21-48](https://user-images.githubusercontent.com/32763112/72200768-85dea380-3475-11ea-83f3-5b8ac9965f52.png)

**Comment by lassekongo83** [comment]
For Ubuntu, use this release for now - https://github.com/lassekongo83/plano-theme/releases/tag/v3.34-2

**Comment by PranavBhattarai** [comment]
@lassekongo83 Ok

**Comment by PranavBhattarai** [comment]
I am closing this issue since 19.10 will dead after few months.
And new in Ubuntu 20.04 LTS release doesn't have this issue.
