### ISSUE TITLE
Gnome shell bug?

### ISSUE THREAD

**Issue by fblais** [lassekongo83/plano-theme#50]
Hi.
Using the dash-to-panel extension here.
The Plano shell theme shows strange on the panel.
It's black on the far right and grey elsewhere.
![plano_screenshot](https://user-images.githubusercontent.com/28492426/72226709-024eb080-3562-11ea-8cf2-e457522128eb.png)

Thanks!

**Comment by lassekongo83** [comment]
The intention was to make the panel behave like this. https://github.com/lassekongo83/plano-theme/blob/master/plano.png?raw=true

But that now requires manual tweaks by the user in d2p settings.

**Comment by fblais** [comment]
Oh, I see, thanks.
I'm using Stilo anyway at the moment.
This one is dark all the way.
