### ISSUE TITLE
After the major update in Plano-Theme (Version 38), the plano-theme no longer works like before. 

### ISSUE THREAD

**Issue by PranavBhattarai** [lassekongo83/plano-theme#53]
How things look like now?
![Screenshot from 2020-07-11 20-20-22](https://user-images.githubusercontent.com/32763112/87226543-2295e580-c3b4-11ea-990a-a5860d5fa466.png)

It used to look black theme behind **Date menu** & **System menu** regardless of what apps/software you are using making rest if the unused panel is completely transparent.

![Screenshot from 2020-07-11 20-24-07](https://user-images.githubusercontent.com/32763112/87226724-7e14a300-c3b5-11ea-92bf-103c8d82472d.png)

P.S: Plano-theme needs an update fix.

**Comment by lassekongo83** [comment]
It's no longer possible to apply a custom style to `#panelRight` in new versions of dash to panel. So I'll have to remove that style. You can make a custom style that adds a black background to the `.clock-display` and `.panel-status-indicators-box` classes, but it will leave a spacing between the indicators and the clock.
