### ISSUE TITLE
problem building the theme

### ISSUE THREAD

**Issue by fblais** [lassekongo83/plano-theme#59]
Getting the same problem with Plano and Stajl's newer code when trying to build them from scratch:

The Meson build system
Version: 0.49.2
Source dir: /home/francois/Téléchargements/plano-theme
Build dir: /home/francois/Téléchargements/plano-theme/build
Build type: native build
Project name: Plano
Project version: undefined
Build machine cpu family: x86_64
Build machine cpu: x86_64
Program sassc found: YES (/usr/bin/sassc)
Configuring index.theme using configuration

gtk/src/Plano/gtk-4.0/meson.build:25:4: ERROR:  Tried to create target "generate_gtk", but a target of that name already exists.

A full log can be found at /home/francois/Téléchargements/plano-theme/build/meson-logs/meson-log.txt

Content of the log:
Build started at 2021-05-09T14:57:42.167525
Main binary: /usr/bin/python3
Python system: Linux
The Meson build system
Version: 0.49.2
Source dir: /home/francois/Téléchargements/plano-theme
Build dir: /home/francois/Téléchargements/plano-theme/build
Build type: native build
Project name: Plano
Project version: undefined
Build machine cpu family: x86_64
Build machine cpu: x86_64
Program sassc found: YES (/usr/bin/sassc)
Configuring index.theme using configuration

gtk/src/Plano/gtk-4.0/meson.build:25:4: ERROR:  Tried to create target "generate_gtk", but a target of that name already exists.

System:
LMDE 4. (Linux Mint based on Debian stable)
Cinnamon DE.
GTK 3.24.5

Thanks in advance!

**Comment by lassekongo83** [comment]
Your meson version is most likely too old. It needs to be at version 0.53.2 or later.

https://github.com/lassekongo83/plano-theme/releases have the releases for older versions.

**Comment by fblais** [comment]
Oh, ok, thanks.
I think I'll modify my sources.list to get Debian testing then.
It provides Meson 0.56.2.
