### ISSUE TITLE
button highlight bug?

### ISSUE THREAD

**Issue by fblais** [lassekongo83/plano-theme#60]
Hi.
I was able to get the Plano theme in dark mode.
I had previously tried following your instructions but it didn't work.
Under Ubuntu 20.04LTS, Gnome DE.
Anyway, I noticed that in Nautlius, three toolbar buttons don't have the blue line at the right when they have a focus.
I'm trying to upload pictures.
![screen1](https://user-images.githubusercontent.com/28492426/120251834-c0a2d080-c250-11eb-870a-deac7455a069.png)
![screen2](https://user-images.githubusercontent.com/28492426/120251848-c698b180-c250-11eb-8eb6-5b0c65729e51.png)
![screen3](https://user-images.githubusercontent.com/28492426/120251858-cac4cf00-c250-11eb-8ebb-14f6e44087b8.png)
The buttons on the right of those are okay, their left side has the blue line. (not pictured)

Thanks in advance!

**Comment by lassekongo83** [comment]
Box-shadows can't overlap linked buttons, so there's nothing that can be done afaik.

**Comment by fblais** [comment]
Ok, thanks.
I thought the buttons were too close, or could simply be moved by 1 or 2 pixels.
